# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "35783ffed69ae8e466d44b2ea63e7144"
name = "Low Stock Alert"
application_url = "https://lowstockalert-shopify.vercel.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locations,read_products"

[auth]
redirect_urls = [ "https://lowstockalert-shopify.vercel.app/auth/callback" ]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "inventory_levels/update" ]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[build]
automatically_update_urls_on_dev = true
